name: Publish to Github, Curseforge, Modrinth
on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:

      - name: Publish
        uses: Kir-Antipov/mc-publish@v3.3

        with:
            curseforge-id: 1344162
            curseforge-token: ${{ secrets.PUBLISH_CURSEFORGE_TOKEN }}

            modrinth-id: 5e00yMVd
            modrinth-token: ${{ secrets.PUBLISH_MODRINTH_TOKEN }}

            github-tag: "v${{env.VERSION}}"
            github-token: ${{ secrets.PUBLISH_GITHUB_TOKEN }}

            name: "${{env.RELEASE_NAME}}"
            version: "${{env.VERSION}}"
            version-type: beta
            changelog-file: CHANGELOG.md

            loaders: fabric
            game-versions: "${{env.MINECRAFT_VERSION}}"
            java: "${{env.JAVA_VERSION}}"

