name: Publish to Github, Curseforge, Modrinth
on: [workflow_dispatch]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MINECRAFT_VERSION: 1.21.1
      JAVA_VERSION: 21
      VERSION: 1.0.1+1.21.1
      RELEASE_NAME: Eggmod 1.0.1 for Fabric 1.21.1
      MODRINTH_TOKEN: ${{ secrets.PUBLISH_MODRINTH_TOKEN }}
      CURSEFORGE_TOKEN: ${{ secrets.PUBLISH_CURSEFORGE_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.PUBLISH_GITHUB_TOKEN }}

    steps:
      - name: Check Env Variables
        run: env

      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Publish
        uses: Kir-Antipov/mc-publish@v3.3
        with:
            curseforge-id: 1344162
            curseforge-token: "${{env.CURSEFORGE_TOKEN}}"

            modrinth-id: 5e00yMVd
            modrinth-token: "${{env.MODRINTH_TOKEN}}"

            github-tag: "v${{env.VERSION}}"
            github-token: "${{env.GITHUB_TOKEN}}"

            name: "${{env.RELEASE_NAME}}"
            version: "${{env.VERSION}}"
            version-type: beta
            changelog-file: CHANGELOG.md

            loaders: fabric
            game-versions: "${{env.MINECRAFT_VERSION}}"
            java: "${{env.JAVA_VERSION}}"

